DishUp/Controllers/JsonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DishUp.Controllers
{
    public class JsonController : BaseController
    {
        // GET: Json
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public JsonResult GetSupplies(string searchTerm, int pageSize, int pageNumber)
        {
            var select2Repository = new Select2Repository();

            var result = select2Repository.GetSelect2PagedResult(searchTerm, pageSize, pageNumber, "SUPPLIE");

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetSupplierSupplie(string searchTerm, int pageSize, int pageNumber, int ID)
        {
            var select2Repository = new Select2Repository();

            var result = select2Repository.GetSelect2PagedResult(searchTerm, pageSize, pageNumber, "SUPPLIER_SUPPLIE",ID);

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetPackaging(string searchTerm, int pageSize, int pageNumber)
        {
            var select2Repository = new Select2Repository();

            var result = select2Repository.GetSelect2PagedResult(searchTerm, pageSize, pageNumber, "PACKAGING");

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetSupplier(string searchTerm, int pageSize, int pageNumber)
        {
            var select2Repository = new Select2Repository();

            var result = select2Repository.GetSelect2PagedResult(searchTerm, pageSize, pageNumber, "SUPPLIER");

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

DishUp/Controllers/PackagingSuppliesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DishUp;

namespace DishUp.Controllers
{
    public class PackagingSuppliesController : BaseController
    {
        private dishupEntities db = new dishupEntities();

        // GET: PackagingSupplies
        public ActionResult Index()
        {
            var iNSUMO_PACKAGING = db.INSUMO_PACKAGING.Include(i => i.INSUMO).Include(i => i.PACKAGING).Include(i=>i.INSUMO.MEDIDA);
            return View(iNSUMO_PACKAGING.ToList());
        }

        // GET: PackagingSupplies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            INSUMO_PACKAGING iNSUMO_PACKAGING = db.INSUMO_PACKAGING.Find(id);
            if (iNSUMO_PACKAGING == null)
            {
                return HttpNotFound();
            }
            return View(iNSUMO_PACKAGING);
        }

        // GET: PackagingSupplies/Create
        public ActionResult Create()
        {
            ViewBag.ID_INSUMO = new SelectList(db.INSUMOes, "ID_INSUMO", "NOMBRE");
            ViewBag.ID_PACKAGING = new SelectList(db.PACKAGINGs, "ID_PACKAGING", "NAME");
            return View();
        }

        // POST: PackagingSupplies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_INSUMO_PACKAGING,ID_INSUMO,ID_PACKAGING,QUANTITY,maxPerson,minPerson,ACTIVE")] INSUMO_PACKAGING iNSUMO_PACKAGING)
        {
            if (ModelState.IsValid)
            {
                db.INSUMO_PACKAGING.Add(iNSUMO_PACKAGING);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_INSUMO = new SelectList(db.INSUMOes, "ID_INSUMO", "NOMBRE", iNSUMO_PACKAGING.ID_INSUMO);
            ViewBag.ID_PACKAGING = new SelectList(db.PACKAGINGs, "ID_PACKAGING", "NAME", iNSUMO_PACKAGING.ID_PACKAGING);
            return View(iNSUMO_PACKAGING);
        }

        // GET: PackagingSupplies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            INSUMO_PACKAGING iNSUMO_PACKAGING = db.INSUMO_PACKAGING.Find(id);
            if (iNSUMO_PACKAGING == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_INSUMO = new SelectList(db.INSUMOes, "ID_INSUMO", "NOMBRE", iNSUMO_PACKAGING.ID_INSUMO);
            ViewBag.ID_PACKAGING = new SelectList(db.PACKAGINGs, "ID_PACKAGING", "NAME", iNSUMO_PACKAGING.ID_PACKAGING);
            return View(iNSUMO_PACKAGING);
        }

        // POST: PackagingSupplies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_INSUMO_PACKAGING,ID_INSUMO,ID_PACKAGING,QUANTITY,maxPerson,minPerson,ACTIVE")] INSUMO_PACKAGING iNSUMO_PACKAGING)
        {
            if (ModelState.IsValid)
            {
                iNSUMO_PACKAGING.ACTIVE = 1;
                db.Entry(iNSUMO_PACKAGING).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_INSUMO = new SelectList(db.INSUMOes, "ID_INSUMO", "NOMBRE", iNSUMO_PACKAGING.ID_INSUMO);
            ViewBag.ID_PACKAGING = new SelectList(db.PACKAGINGs, "ID_PACKAGING", "NAME", iNSUMO_PACKAGING.ID_PACKAGING);
            return View(iNSUMO_PACKAGING);
        }

        // GET: PackagingSupplies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            INSUMO_PACKAGING iNSUMO_PACKAGING = db.INSUMO_PACKAGING.Find(id);
            if (iNSUMO_PACKAGING == null)
            {
                return HttpNotFound();
            }
            return View(iNSUMO_PACKAGING);
        }

        // POST: PackagingSupplies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            INSUMO_PACKAGING iNSUMO_PACKAGING = db.INSUMO_PACKAGING.Find(id);
            iNSUMO_PACKAGING.ACTIVE = 0;
            db.Entry(iNSUMO_PACKAGING).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DishUp/Views/PackagingSupplies/Create.cshtml
@model DishUp.INSUMO_PACKAGING

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>INSUMO_PACKAGING</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_INSUMO, "ID_INSUMO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_INSUMO", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_INSUMO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_PACKAGING, "ID_PACKAGING", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_PACKAGING", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_PACKAGING, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QUANTITY, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QUANTITY, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QUANTITY, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maxPerson, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maxPerson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maxPerson, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.minPerson, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.minPerson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.minPerson, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ACTIVE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ACTIVE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ACTIVE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section scripts{}

DishUp/Views/PackagingSupplies/Delete.cshtml
@model DishUp.INSUMO_PACKAGING

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>INSUMO_PACKAGING</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QUANTITY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QUANTITY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.maxPerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maxPerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.minPerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.minPerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ACTIVE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ACTIVE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.INSUMO.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.INSUMO.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PACKAGING.IMAGE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PACKAGING.IMAGE)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>


@section scripts{}

DishUp/Views/PackagingSupplies/Details.cshtml
@model DishUp.INSUMO_PACKAGING

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>INSUMO_PACKAGING</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QUANTITY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QUANTITY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.maxPerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maxPerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.minPerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.minPerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ACTIVE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ACTIVE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.INSUMO.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.INSUMO.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PACKAGING.IMAGE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PACKAGING.IMAGE)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_INSUMO_PACKAGING }) |
    @Html.ActionLink("Back to List", "Index")
</p>


@section scripts{}

DishUp/Views/PackagingSupplies/Edit.cshtml
@model DishUp.INSUMO_PACKAGING

@{
    ViewBag.Title = "Edit";
}

<h2>PACKAGING SUPPLIE</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_INSUMO_PACKAGING)

        <div class="form-group">
            @Html.Label("SUPPLIE", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_INSUMO", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_INSUMO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("PACKAGING", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.DropDownList("ID_PACKAGING", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_PACKAGING, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QUANTITY, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QUANTITY, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QUANTITY, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("MIN PERSONS", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.minPerson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.minPerson, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("MAX PERSONS", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.maxPerson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maxPerson, "", new { @class = "text-danger" })
            </div>
        </div>



    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>

}
@Html.Hidden("urlSupplie", Url.Action("GetSupplies", "Json"))
@Html.Hidden("urlPackaging", Url.Action("GetPackaging", "Json"))

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/Packaging.js"></script>

@section scripts{}

DishUp/Views/PackagingSupplies/Index.cshtml
@model IEnumerable<DishUp.INSUMO_PACKAGING>

@{
    ViewBag.Title = "Index";
}
<br />

<p>
    @Html.ActionLink("New Packaging", "Create", "", new { @class = "btn btn-lg btn-success" })

</p>
<table class="table" id="packagingSupplies" data-paging="true" data-filtering="true" data-sorting="true" data-state="true">
    <tr>
        <th>
            SUPPLIE
        </th>
        <th>
            PACKAGING
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QUANTITY)
        </th>
        <th>
            MIN PERSONS
        </th>
        <th>
            MAX PERSONS
        </th>



        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.INSUMO.NOMBRE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PACKAGING.NAME)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QUANTITY) @if (item.INSUMO.MEDIDA != null)
                {@item.INSUMO.MEDIDA.NOMBRE;
            }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.minPerson)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.maxPerson)
            </td>



            <td>
                <a href="@Url.Action("Edit", "PackagingSupplies",new { id = item.ID_INSUMO_PACKAGING })" class="btn btn-primary">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    Edit
                </a>
                <a href="@Url.Action("Delete", "PackagingSupplies",new { id = item.ID_INSUMO_PACKAGING})" class="btn btn-danger">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    Delete
                </a>
            </td>
        </tr>
    }

</table>

@section scripts{}