DishUp/Controllers/PackagingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DishUp;

namespace DishUp.Controllers
{
    public class PackagingController : BaseController
    {
        private dishupEntities db = new dishupEntities();

        // GET: Packaging
        public ActionResult Index()
        {
            return View(db.PACKAGINGs.ToList());
        }

        // GET: Packaging/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PACKAGING pACKAGING = db.PACKAGINGs.Find(id);
            if (pACKAGING == null)
            {
                return HttpNotFound();
            }
            return View(pACKAGING);
        }

        // GET: Packaging/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Packaging/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_PACKAGING,IMAGE,NAME,UNIT_PRICE,WHOLESALE_PRICE,ACTIVE")] PACKAGING pACKAGING)
        {
            if (ModelState.IsValid)
            {
                db.PACKAGINGs.Add(pACKAGING);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pACKAGING);
        }

        // GET: Packaging/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PACKAGING pACKAGING = db.PACKAGINGs.Find(id);
            if (pACKAGING == null)
            {
                return HttpNotFound();
            }
            return View(pACKAGING);
        }

        // POST: Packaging/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_PACKAGING,IMAGE,NAME,UNIT_PRICE,WHOLESALE_PRICE,ACTIVE")] PACKAGING pACKAGING)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pACKAGING).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pACKAGING);
        }

        // GET: Packaging/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PACKAGING pACKAGING = db.PACKAGINGs.Find(id);
            if (pACKAGING == null)
            {
                return HttpNotFound();
            }
            return View(pACKAGING);
        }
        public ActionResult GetImage(int ID)
        {
            String imgSource = db.PACKAGINGs.Where(x => x.ID_PACKAGING == ID).Select(x => x.IMAGE).First();
            return PartialView("_Uploader", imgSource);
        }
        public ActionResult UploadFile(FineUpload upload, int? id)
        {
            // asp.net mvc will set extraParam1 and extraParam2 from the params object passed by Fine-Uploader
            //  return View();
            PACKAGING pr = db.PACKAGINGs.Where(x => x.ID_PACKAGING == id).First();

            var dir = Server.MapPath("~/UploadPictures/");
            var filePath = Path.Combine(dir, upload.Filename);
            pr.IMAGE = "../../UploadPictures/" + upload.Filename;
            db.Entry(pr).State = EntityState.Modified;
            db.SaveChanges();
            try
            {
                upload.SaveAs(filePath);

            }
            catch (Exception ex)
            {
                return new FineUploaderResult(false, error: ex.Message);
            }

            //// the anonymous object in the result below will be convert to json and set back to the browser
            return new FineUploaderResult(true, new { extraInformation = pr.IMAGE });
        }

        // POST: Packaging/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PACKAGING pACKAGING = db.PACKAGINGs.Find(id);
            db.PACKAGINGs.Remove(pACKAGING);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DishUp/Views/Packaging/Create.cshtml
@model DishUp.PACKAGING

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PACKAGING</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IMAGE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IMAGE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UNIT_PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UNIT_PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UNIT_PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WHOLESALE_PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WHOLESALE_PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WHOLESALE_PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ACTIVE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ACTIVE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ACTIVE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section scripts{}

DishUp/Views/Packaging/Delete.cshtml
@model DishUp.PACKAGING

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PACKAGING</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IMAGE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IMAGE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UNIT_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UNIT_PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WHOLESALE_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WHOLESALE_PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ACTIVE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ACTIVE)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DishUp/Views/Packaging/Details.cshtml
@model DishUp.PACKAGING

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PACKAGING</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IMAGE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IMAGE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UNIT_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UNIT_PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WHOLESALE_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WHOLESALE_PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ACTIVE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ACTIVE)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_PACKAGING }) |
    @Html.ActionLink("Back to List", "Index")
</p>


@section scripts{}

DishUp/Views/Packaging/Edit.cshtml
@model DishUp.PACKAGING

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-md-6" style="float:left;">
        <h2>Edit Packaging </h2>

    </div>
    <div class="col-md-6" style="float:right;">
        <h2>@Html.ActionLink("Back to Packaging List", "Index", "", new { @class = "btn btn-default" })</h2>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_PACKAGING)

        <div class="form-group">
            <div class="row">
                <div class="col-lg-2">
                    <div id="imgLoader">
                        @Html.Action("GetImage", "Packaging", new { ID = Model.ID_PACKAGING })

                    </div>

                    @*<img src="@Model.IMAGEN" width="50" height="50" alt="Alternate Text" />*@

                </div>
                <div class="col-lg-10">
                    @using (Ajax.BeginForm("UploadFile", "PACKAGING", new { id = Model.ID_PACKAGING }, new AjaxOptions
                    {
                        UpdateTargetId = "imgLoader",
                        HttpMethod = "POST",
                        InsertionMode = InsertionMode.Replace,
                        OnSuccess = ""

                    }, new { @class = "form-horizontal" }))
                    {
                        <div id="fine-uploader">

                        </div>
                    }
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">UNIT PRICE </label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.UNIT_PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UNIT_PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">WHOLESALE PRICE</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.WHOLESALE_PRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WHOLESALE_PRICE, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section scripts{}

DishUp/Views/Packaging/Index.cshtml
@model IEnumerable<DishUp.PACKAGING>

@{
    ViewBag.Title = "Packaging";
}

<br />
<p>
    @Html.ActionLink("Add Packaging", "Create", "", new { @class = "btn btn-lg btn-success" })

</p>
<table class="table" id="packagingTable" data-paging="true" data-filtering="true" data-sorting="true" data-state="true">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IMAGE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UNIT_PRICE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WHOLESALE_PRICE)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IMAGE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UNIT_PRICE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WHOLESALE_PRICE)
            </td>

            <td>

                <a href="@Url.Action("Edit", "Packaging",new { id = item.ID_PACKAGING })" class="btn btn-primary">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    Edit
                </a>
                <a href="@Url.Action("Delete", "Packaging",new { id = item.ID_PACKAGING })" class="btn btn-danger">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    Delete
                </a>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.ID_MENU }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Details", "Details", new { id = item.ID_MENU }, new { @style = "display:none;" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID_MENU }, new { @class = "btn btn-danger" })*@
            </td>
        </tr>
    }

</table>


@section scripts{}