DishUp/Controllers/InsumoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using DishUp;
using Microsoft.AspNet.Identity;

namespace DishUp.Controllers
{
    public class InsumoController : BaseController
    {
        private dishupEntities db = new dishupEntities();

        // GET: Insumo
        public ActionResult Index()
        {

            var id = User.Identity.GetUserId();
            var iNSUMOes = db.USER_SUPPLIER_INSUMO.Include(i => i.MEDIDA).Include(i => i.MEDIDA1).Where(x=>x.ID_USER == id && x.ACTIVE ==true);
            return View(iNSUMOes.ToList());
        }

        // GET: Insumo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER_SUPPLIER_INSUMO iNSUMO = db.USER_SUPPLIER_INSUMO.Find(id);
            if (iNSUMO == null)
            {
                return HttpNotFound();
            }
            return View(iNSUMO);
        }

        // GET: Insumo/Create
        public ActionResult Create()
        {
            ViewBag.ID_MEDIDA_PACKAGE = new SelectList(db.MEDIDAs, "ID_MEDIDA", "NOMBRE");
            ViewBag.ID_USER_SUPPLIER = new SelectList(db.USER_SUPPLIER, "ID_USER_SUPPLIER", "NAME");
            ViewBag.ID_CUSTOM_UNIT = new SelectList(db.CUSTOM_UNIT, "ID_CUSTOM_UNIT", "NAME");
            return View(new USER_SUPPLIER_INSUMO());
        }

        // POST: Insumo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_MEDIDA_PACKAGE,ID_USER_SUPPLIER,ID_CUSTOM_UNIT,UNIT_WEIGHT,ID_,NAME,PRICE,QUANTITY_PACKAGE,IS_BOX,IS_PACKAGE,QUANTITY_BOX,QUANTITY,CODE")] USER_SUPPLIER_INSUMO iNSUMO, string submitButton)
        {
            bool isBox = false;
            decimal individualPrice;

            if (ModelState.IsValid)
            {
                iNSUMO.ID_USER = User.Identity.GetUserId();
                iNSUMO.ACTIVE = true;

                if (iNSUMO.QUANTITY == null)
                {
                    iNSUMO.QUANTITY = 1;
                }
                
                
                if (iNSUMO.IS_BOX == true) 
                {
                    /*
                     If this option is checked it means the product is sold in a box/package  with multiple items inside. For example: A box of Wine that brings 6 bottles of wine inside.
                     So for this case the information should be input as follows:

                    NAME: BOX OF WINE.
                    QUANTITY: 1 ( Since it's 1 box) 
                    QUANTITY_BOX: 6.
                    PRICE: $x price.
                    
                    Another example would be 1 box of burgers that contains 6 packages of 4 burgers each, with a total of 24 burgers. So the information should be input as follows:

                    NAME: BOX OF BURGUER.
                    QUANTITY: 4 ( This is the amount that brings each package.) 
                    QUANTITY_BOX: 6. ( It comes with 6 packages)
                    PRICE: $x price.
                    
                    */

                    isBox = true;
                    decimal totalQuantity = Convert.ToDecimal((iNSUMO.QUANTITY * iNSUMO.QUANTITY_BOX));
                    individualPrice = Convert.ToDecimal(iNSUMO.PRICE / totalQuantity);
                }
                else
                {
                    individualPrice = Convert.ToDecimal(iNSUMO.PRICE / iNSUMO.QUANTITY);
                }
                  
                iNSUMO.INDIVIDUAL_PRICE = individualPrice;
                db.USER_SUPPLIER_INSUMO.Add(iNSUMO);

            
                db.SaveChanges();
                Success(string.Format(" The ingredient <b>{0}</b> was successfully added to the database.", iNSUMO.NAME), true);
                switch (submitButton)
                {
                    case "Save and Create":
                        return RedirectToAction("Create");

                        break;
                    case "Save":
                        return RedirectToAction("Index");

                        break;
                }
            }
            IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
            ViewBag.ID_MEDIDA_PACKAGE = new SelectList(db.MEDIDAs, "ID_MEDIDA", "NOMBRE", iNSUMO.ID_MEDIDA_PACKAGE);
            ViewBag.ID_CUSTOM_UNIT = new SelectList(db.CUSTOM_UNIT, "ID_CUSTOM_UNIT", "NAME");

            return View(iNSUMO);
        }

        // GET: Insumo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER_SUPPLIER_INSUMO iNSUMO = db.USER_SUPPLIER_INSUMO.Find(id);
            if (iNSUMO == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_MEDIDA_PACKAGE = new SelectList(db.MEDIDAs, "ID_MEDIDA", "NOMBRE", iNSUMO.ID_MEDIDA_PACKAGE);
            ViewBag.ID_USER_SUPPLIER = new SelectList(db.USER_SUPPLIER, "ID_USER_SUPPLIER", "NAME", iNSUMO.ID_USER_SUPPLIER);
            ViewBag.ID_CUSTOM_UNIT = new SelectList(db.CUSTOM_UNIT, "ID_CUSTOM_UNIT", "NAME",iNSUMO.ID_CUSTOM_UNIT);

            return View(iNSUMO);
        }

        // POST: Insumo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_USER_SUPPLIER,ID_USER_SUPPLIER_INSUMO,UNIT_WEIGHT,ID_MEDIDA_PACKAGE,ID_CUSTOM_UNIT,NAME,PRICE,QUANTITY_PACKAGE,IS_BOX,IS_PACKAGE,QUANTITY_BOX,QUANTITY,CODE")] USER_SUPPLIER_INSUMO iNSUMO)
        {

           
            if (ModelState.IsValid)
            {
         
                var idUser = User.Identity.GetUserId();
                iNSUMO.ID_USER = idUser;
                iNSUMO.ACTIVE = true;
                if(iNSUMO.QUANTITY == null)
                {
                    iNSUMO.QUANTITY = 1;
                }
                bool isBox = false;
                decimal individualPrice;
                if (iNSUMO.IS_BOX == true)
                {
                    isBox = true;
                    decimal totalQuantity = Convert.ToDecimal((iNSUMO.QUANTITY * iNSUMO.QUANTITY_BOX));
                    individualPrice = Convert.ToDecimal(iNSUMO.PRICE / totalQuantity);
                }
                else
                {
                    individualPrice = Convert.ToDecimal(iNSUMO.PRICE / iNSUMO.QUANTITY);
                }
                iNSUMO.INDIVIDUAL_PRICE = individualPrice;
                    db.Entry(iNSUMO).State = EntityState.Modified;
                db.SaveChanges();
                Success(String.Format("The ingredient {0} was updated correctly.", iNSUMO.NAME));

                return RedirectToAction("Index");
            }
            ViewBag.ID_MEDIDA_PACKAGE = new SelectList(db.MEDIDAs, "ID_MEDIDA", "NOMBRE", iNSUMO.ID_MEDIDA_PACKAGE);
            ViewBag.ID_CUSTOM_UNIT = new SelectList(db.CUSTOM_UNIT, "ID_CUSTOM_UNIT", "NAME", iNSUMO.ID_MEDIDA_PACKAGE);
            ViewBag.ID_USER_SUPPLIER = new SelectList(db.USER_SUPPLIER, "ID_USER_SUPPLIER", "NAME", iNSUMO.ID_USER_SUPPLIER);

            IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);

            StringBuilder str = new StringBuilder();
            str.AppendLine("The following error has ocurred: <br/>");
            str.AppendLine("<ul>");

            foreach (var it in allErrors)
            {
                str.AppendLine("<li>" + it.ErrorMessage.ToString() + "</li>");
            }
            str.AppendLine("</ul>");

            Danger(str.ToString(), true);
            return View(iNSUMO);
        }

        // GET: Insumo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER_SUPPLIER_INSUMO iNSUMO = db.USER_SUPPLIER_INSUMO.Find(id);
            if (iNSUMO == null)
            {
                return HttpNotFound();
            }
            return View(iNSUMO);
        }

        // POST: Insumo/Delete/5
        public ActionResult DeleteConfirmed(int id)
        {
            USER_SUPPLIER_INSUMO iNSUMO = db.USER_SUPPLIER_INSUMO.Find(id);
            iNSUMO.ACTIVE = false;
            db.Entry(iNSUMO).State = EntityState.Modified;
            db.SaveChanges();
            Success(String.Format("The ingredient {0} was removed correctly.", iNSUMO.NAME));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public JsonResult GetSupplierRelated(string searchTerm, int pageSize, int pageNumber)
        {
            var select2Repository = new Select2Repository();

            var result = select2Repository.GetSelect2PagedResult(searchTerm, pageSize, pageNumber, "SUPPLIER_SUPLIE_RELATED");

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DishUp/Views/Insumo/Create.cshtml
@model DishUp.USER_SUPPLIER_INSUMO

@{
    ViewBag.Title = "Create";
}
<!--Page Style Section-->
<link href="~/Content/select2.min.css" rel="stylesheet" />
<link href="~/Content/Custom.css" rel="stylesheet" />

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Create</h3>
            </div>


            @using (Html.BeginForm("Create", "Insumo", FormMethod.Post, new { @class = "needs-validation", @novalidate = "novalidate" }))
            {
                @Html.AntiForgeryToken()

                <div class="box-body">

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("SUPPLIER")
                                @Html.DropDownList("ID_USER_SUPPLIER", null, "Select Supplier", htmlAttributes: new { @class = "form-control select2", @id = "insuSupplier", @required = "required" })
                                <div class="invalid-feedback">
                                    Please choose supplier.
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Product Name")
                                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @name = "NAME", placeholder = "Product Name", @class = "form-control" } })

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Code")

                                @Html.EditorFor(model => model.CODE, new { htmlAttributes = new { placeholder = "Code", @class = "form-control" } })
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group" id="isBoxCheckBox">
                                @Html.CheckBox("IS_BOX", Model.IS_BOX)
                                <label for="IS_BOX">Does it contain multiple items?</label>
                            </div>
                        </div>
                    </div>


                    @*<div id="isBoxSupplie" style="display:none;">
                    <div class="row">


                        <div class="col-md-6">
                            <div class="form-group" style="display:none;">

                            </div>
                        </div>
                    </div>
                </div>*@




                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Quantity")

                                @Html.EditorFor(model => model.QUANTITY, new { htmlAttributes = new { placeholder = "Quantity", @class = "form-control" } })

                            </div>
                        </div>
                        <div class="col-md-6" id="isBoxSupplie" style=" display: none;">
                            <div class="form-group">
                                @Html.Label("Quantity per box")
                                @Html.EditorFor(model => model.QUANTITY_BOX, new { htmlAttributes = new { placeholder = "Quantity per Box", @class = "form-control" } })
                            </div>
                        </div>
                        <div class="col-md-4" style="display:none;">
                            <div class="form-group">
                                @Html.Label("Portion Size")

                                @Html.DropDownList("ID_CUSTOM_UNIT", null, "Portioned Size", htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Unit / Weight")
                                @Html.EditorFor(model => model.UNIT_WEIGHT, new { htmlAttributes = new { placeholder = "Unit Weight", @class = "form-control" } })
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Portioned By")
                                @Html.DropDownList("ID_MEDIDA_PACKAGE", null, "Portioned By", htmlAttributes: new { @class = "form-control select2" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Product Price")
                                @Html.EditorFor(model => model.PRICE, new { htmlAttributes = new { placeholder = "Price $", @class = "form-control" } })
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-10">
                            <div class="form-group">
                                <div class="modal-footer">
                                    <a class="btn btn-secondary" href="@Url.Action("Index","Insumo")">Close</a>
                                    <input type="submit" class="btn btn-success" name="submitButton" value="Save and Create" />
                                    <input type="submit" class="btn btn-success" name="submitButton" value="Save" />
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="form-group" style="display:none;">
                        @Html.CheckBox("IS_PACKAGE", Model.IS_PACKAGE)
                        @*<input type="checkbox" value="@Model.IS_PACKAGE" checked="@Model.IS_PACKAGE" name="IS_PACKAGE" id="IS_PACKAGE" />*@ <span>IS PACKAGE</span>

                    </div>
                    @if (Convert.ToBoolean(Model.IS_PACKAGE))
                    {
                        <div id="isPackageSupplie">
                            <div class="form-group">
                                @Html.EditorFor(model => model.QUANTITY_PACKAGE, new { htmlAttributes = new { placeholder = "Quantity per Package", @class = "form-control" } })

                            </div>

                        </div>
                    }
                    else
                    {
                        <div id="isPackageSupplie" style="display:none;">
                            <div class="form-group">
                                @Html.EditorFor(model => model.QUANTITY_PACKAGE, new { htmlAttributes = new { placeholder = "Quantity per Package", @class = "form-control" } })

                            </div>

                        </div>

                    }

                </div>
            }
        </div>
    </div>
</div>




<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    <script src="~/Scripts/select2.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $("input[name='IS_PACKAGE']").on("change", function () {
            $("#priceUnit").toggle(this.checked);
        });

    </script>
    <script type="text/javascript">
        function sum() {
            var txtFirstNo = document.getElementById('PRICE').value;
            var txtSecondNo = document.getElementById('QUANTITY_PACKAGE').value;
            var result = parseInt(txtFirstNo) / parseInt(txtSecondNo);
            if (!isNaN(result)) {
                //document.getElementById('PRICE_PER_UNIT').value = result;
            }
        }
        $(document).ready(function () {
            $('.select2').select2();

            $('#IS_PACKAGE').change(function () {
                $('#isPackageSupplie').toggle(this.checked);
            }).change(); //ensure visible state matches initially
            $('#IS_BOX').change(function () {

                $('#isBoxSupplie').toggle(this.checked);
            }).change();



            $(function () {
                'use strict';
                window.addEventListener('load', function () {
                    // Fetch all the forms we want to apply custom Bootstrap validation styles to
                    var forms = document.getElementsByClassName('needs-validation');
                    // Loop over them and prevent submission
                    var validation = Array.prototype.filter.call(forms, function (form) {
                        form.addEventListener('submit', function (event) {
                            if (form.checkValidity() === false) {
                                event.preventDefault();
                                event.stopPropagation();
                            }
                            form.classList.add('was-validated');
                        }, false);
                    });
                }, false);
            });
        });

    </script>

}

DishUp/Views/Insumo/Delete.cshtml
@model DishUp.INSUMO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>INSUMO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ACTIVE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ACTIVE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WHOLESALE_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WHOLESALE_PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SALE_PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SALE_PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QUANTITY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QUANTITY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MEDIDA.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MEDIDA.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MEDIDA1.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MEDIDA1.NOMBRE)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

@section scripts{}

DishUp/Views/Insumo/Edit.cshtml
@model DishUp.USER_SUPPLIER_INSUMO


@{
    ViewBag.Title = "Index";
}
<!--Page Style Section-->
<link href="~/Content/select2.min.css" rel="stylesheet" />
<link href="~/Content/Custom.css" rel="stylesheet" />
<style>
    #isBoxCheckBox {
        margin-top: 6%;
    }
</style>


<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title text-gray-800">Edit Product</h3>
            </div>


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.ID_USER_SUPPLIER_INSUMO)
                <div class="box-body">

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("SUPPLIER")
                                @Html.DropDownList("ID_USER_SUPPLIER", null, "Select Supplier", htmlAttributes: new { @class = "form-control select2" })
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Product Name")
                                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @name = "NAME", placeholder = "Product Name", @class = "form-control" } })

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Code")
                                @Html.EditorFor(model => model.CODE, new { htmlAttributes = new { placeholder = "Code", @class = "form-control" } })
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group" id="isBoxCheckBox">
                                @Html.CheckBox("IS_BOX", Model.IS_BOX)
                                <label for="IS_BOX">Does it contain multiple items?</label>
                            </div>
                        </div>
                    </div>


                    @*<div id="isBoxSupplie" style="display:none;">
                            <div class="row">

                                <div class="col-md-6">
                                    <div class="form-group" style="display:none;">
                                        @Html.Label("Portioned By")

                                        @Html.DropDownList("ID_CUSTOM_UNIT", null, "Portioned By", htmlAttributes: new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                        </div>*@



                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Quantity")
                                @Html.EditorFor(model => model.QUANTITY, new { htmlAttributes = new { placeholder = "Quantity", @class = "form-control" } })
                            </div>
                        </div>

                        <div class="col-md-6" id="isBoxSupplie" style="display:none;">
                            <div class="form-group">
                                @Html.Label("Quantity per box")
                                @Html.EditorFor(model => model.QUANTITY_BOX, new { htmlAttributes = new { placeholder = "Quantity per Box", @class = "form-control" } })
                            </div>
                        </div>

                        <div class="col-md-4" style="display:none">
                            <div class="form-group">
                                @Html.Label("Portion Size")

                                @Html.DropDownList("ID_MEDIDA_PACKAGE", null, "Portioned Size", htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Unit / Weight")
                                @Html.EditorFor(model => model.UNIT_WEIGHT, new { htmlAttributes = new { placeholder = "Unit Weight", @class = "form-control" } })
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Portioned By")
                                @Html.DropDownList("ID_MEDIDA_PACKAGE", null, "Portioned By", htmlAttributes: new { @class = "form-control select2" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Product Price")
                                @Html.EditorFor(model => model.PRICE, new { htmlAttributes = new { placeholder = "Price $", @class = "form-control" } })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-10">
                            <div class="form-group">
                                <div class="modal-footer">
                                    <a class="btn btn-secondary" href="@Url.Action("Index","Insumo")">Close</a>
                                    <input type="submit" class="btn btn-success" name="submitButton" value="Update" />
                                </div>

                            </div>
                        </div>
                    </div>



                    <div class="form-group" style="display:none;">
                        @Html.CheckBox("IS_PACKAGE", Model.IS_PACKAGE)
                        @*<input type="checkbox" value="@Model.IS_PACKAGE" checked="@Model.IS_PACKAGE" name="IS_PACKAGE" id="IS_PACKAGE" />*@ <span>IS PACKAGE</span>

                    </div>
                    @if (Convert.ToBoolean(Model.IS_PACKAGE))
                    {
                        <div id="isPackageSupplie">
                            <div class="form-group">
                                @Html.EditorFor(model => model.QUANTITY_PACKAGE, new { htmlAttributes = new { placeholder = "Quantity per Package", @class = "form-control" } })

                            </div>

                        </div>
                    }
                    else
                    {
                        <div id="isPackageSupplie" style="display:none;">
                            <div class="form-group">
                                @Html.EditorFor(model => model.QUANTITY_PACKAGE, new { htmlAttributes = new { placeholder = "Quantity per Package", @class = "form-control" } })

                            </div>

                        </div>

                    }


                </div>
            }
        </div>
    </div>
</div>




@section scripts
{
    <script src="~/Scripts/select2.min.js"></script>
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $('.select2').select2();

            $('#IS_PACKAGE').change(function () {
                $('#isPackageSupplie').toggle(this.checked);
            }).change(); //ensure visible state matches initially
            $('#IS_BOX').change(function () {

                $('#isBoxSupplie').toggle(this.checked);
            }).change();
        });

    </script>
}

DishUp/Views/Insumo/Index.cshtml
@model IEnumerable<DishUp.USER_SUPPLIER_INSUMO>

@{
    ViewBag.Title = "Index";
}

<h2>

    @Html.ActionLink("Add Ingredient", "Create", "", new { @class = "btn btn-success" })
</h2>

<table class="table" id="insumoTable" data-paging="true" data-filtering="true" data-sorting="true" data-state="true">
    <thead>

        <tr>
            <th>
                @Html.Label("Supplie Name")
            </th>

            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NAME)
                </td>


                <td align="right">
                    <a href="@Url.Action("Edit", "Insumo",new { id = item.ID_USER_SUPPLIER_INSUMO })" class="btn btn-primary">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        Edit
                    </a>
                    @*@Ajax.ActionLink("Delete", "DeleteConfirmed", "INSUMO", new { id = item.ID_USER_SUPPLIER_INSUMO }, new AjaxOptions { Confirm = "Are you sure you want to delete this item?", HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "supplieList" }, new { @class = "btn btn-danger iconDelete" })*@

                    <a href="@Url.Action("DeleteConfirmed", "Insumo",new { id = item.ID_USER_SUPPLIER_INSUMO})" onclick="confirm('Are you sure you want to delete this item?');" class="btn btn-danger">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        Delete
                    </a>

</tr>
        }
    </tbody>
</table>
@section scripts {
    <script>
        $(document).ready(function () {
            $('#insumoTable').DataTable();
        });
    </script>

}